name: 'PR check formatting and tests'

on: pull_request

jobs:

  check-formatting:
    name: 'Check formatting'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Run check formatting
        run: sbt scalafmtCheckAll

  test:
    name: 'Run tests'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Run tests
        run: sbt test
