name: 'Release'

on:
  release:
    types: [published]


jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Set release version
        env:
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
      - name: Dump env
        run: env | sort
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
